name: count_down
description: "倒计时"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl_utils: 2.8.7
  cupertino_icons: 1.0.8
  get: 5.0.0-release-candidate-9.2.1
  flutter_screenutil: 5.9.3
  bot_toast: 4.1.3
  logger: 2.5.0
  shared_preferences: 2.3.3
  flutter_keyboard_visibility: 6.0.0
  flutter_svg: 2.0.14
  flutter_utils_code:
    git:
      url: https://github.com/panzhoutao/flutter_utils_code.git
      ref: 0.1.3
  flutter_slidable: ^3.1.1
  scroll_wheel_date_picker: ^0.0.2+1
  sqflite: 2.4.1
  date_format: 2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/empty_data.svg
    - assets/images/item_delete.svg
    - assets/images/item_top.svg
    - assets/images/settings_tag.svg

flutter_intl:
  enabled: true
