/// Generated file. Do not edit.
/// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'count_down';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String COUNTDOWN_ICON_1 = 'assets/countdown_icon/countdown_icon_1.svg';
  static const String COUNTDOWN_ICON_2 = 'assets/countdown_icon/countdown_icon_2.svg';
  static const String COUNTDOWN_ICON_3 = 'assets/countdown_icon/countdown_icon_3.svg';
  static const String COUNTDOWN_ICON_4 = 'assets/countdown_icon/countdown_icon_4.svg';
  static const String COUNTDOWN_ICON_5 = 'assets/countdown_icon/countdown_icon_5.svg';
  static const String EDIT_COUNTDOWN_EDIT_ICON = 'assets/images/edit_countdown_edit_icon.svg';
  static const String EMPTY_DATA = 'assets/images/empty_data.svg';
  static const String ITEM_DELETE = 'assets/images/item_delete.svg';
  static const String ITEM_TOP = 'assets/images/item_top.svg';
  static const String SETTINGS_AGREEMENT = 'assets/images/settings_agreement.svg';
  static const String SETTINGS_FOLLOW = 'assets/images/settings_follow.svg';
  static const String SETTINGS_PRIVACY = 'assets/images/settings_privacy.svg';
  static const String SETTINGS_REVIEW = 'assets/images/settings_review.svg';
  static const String SETTINGS_TAG = 'assets/images/settings_tag.svg';
  static const String SHARE_TAG = 'assets/images/share_tag.svg';
  static const String SHARE_BG_1 = 'assets/shareBg/share_bg_1.webp';
  static const String SHARE_BG_2 = 'assets/shareBg/share_bg_2.webp';
  static const String SHARE_BG_3 = 'assets/shareBg/share_bg_3.webp';
  static const String SHARE_BG_4 = 'assets/shareBg/share_bg_4.webp';
  static const String SHARE_BG_5 = 'assets/shareBg/share_bg_5.webp';
}
